### ISSUE TITLE
Failed to handle action: plugin_bookcreator_addtobook

### ISSUE THREAD

**Issue by lrosdahl-documentation** [Klap-in/dokuwiki-plugin-bookcreator#121]
I'm getting the following error (see attached also) when clicking **Add to book**: Failed to handle action: plugin_bookcreator_addtobook

This is only happening on a couple of pages. When I re-install the Bookcreator plugin, the icon for **Add to book** does not appear in the page tools sidebar for those pages that were getting the error.

I'm on Release 2018-04-22b "Greebo" and the latest release of Bookcreator (2016-08-11). 

Thank you.

**Comment by sabrinasonno** [comment]
Hi
I have the same problem. I don't see the icon in all pages
The version is  DokuWiki version: Release 2018-04-22b "Greebo"

Can anybody help us?
Thank you

**Comment by Klap-in** [comment]
Do you have any error message? In web server log, or in console of your browser (reachable via 'Inspect' in right-mouse-button menu)

Does it make a difference if you use a different browser?

**Comment by lrosdahl-documentation** [comment]
I don't see anything unusual in the browser console or the server logs. It does seem to be an issue where `style="display:none"` is being added to the list item. Maybe something to do with this? 

![image](https://user-images.githubusercontent.com/35460474/68713211-f4c97a00-0562-11ea-88c8-5467092b0ab0.png)

**Comment by coldscientist** [comment]
I was receiving this error into "Vector" template.
It was happening because the jQuery associates the Bookcreator link/button with the "plugin_bookcreator__addtobook" class. In my case, it was happening because jQuery (throught ``script.js`` file available at Bookcreator plugin root directory) couldn't find the class "plugin_bookcreator__addtobook" (add/remove pages to the book), so instead of adding/remove pages to the book on-the-fly (without reloading the page, as it happens with any other template), the web browser was redirecting to the page ``https://wiki.example.com/doku.php?id=[pageid]&do=plugin_bookcreator__addtobook`` . Apparently the javascript doesn't trigger any error to the console when the class element "plugin_bookcreator__addtobook" doesn't exists into the page.

It was working with any other template because the Bookcreator link/button is created hooking ``MENU_ITEMS_ASSEMBLY`` DokuWiki event, but the Vector template doesn't handle this event, so I was using the code below to add the Bookcreator manually at my template:

```
//custom plugin tab
$items = (new \dokuwiki\Menu\PageMenu())->getItems();
foreach($items as $item) {
    $query = parse_url($item->getLink(), PHP_URL_QUERY);
    parse_str($query, $params);
 
    if(!preg_match("/\b(&do=edit|&do=revisions|&do=backlink|&do=export_odt|&do=export_pdf|dokuwiki__top)\b/", $item->getLink())) {
        $_vector_tabs_right["tab-" . $params['do']]["text"]     = $item->getLabel();
        $_vector_tabs_right["tab-" . $params['do']]["href"]     = $item->getLink();
        $_vector_tabs_right["tab-" . $params['do']]["nofollow"] = true;
    }
}
```

This code parses the PageItems and add the third-party plugins to the Vector template tab. The Bookcreator link was showing as expected, but wasn't working with the "Failed to handle action: plugin_bookcreator__addtobook" error. The solution was adding the following line to the code:

```
        $_vector_tabs_right["tab-" . $params['do']]["class"] = $params['do'];
```

This last line added the class "plugin_bookcreator__addtobook" to the link and it started working normally. I did tried to use a user custom JS to append the "plugin_bookcreator__addtobook" class after the page loading, but it fails, probably because the Bookcreator JS was trying to hook the element with "plugin_bookcreator__addtobook" class before the parsing my user custom JS, so it fails. So yeah, if you're receiving this error with your template, you'll need to edit your template file directly.

**Comment by Klap-in** [comment]
Ah, I haven’t tested templates which doesn’t use the newest page tool menus. This is worth a look.

**Comment by Klap-in** [comment]
If I add the extra pagemenu-entries from plugins with the code from example at:
https://github.com/arsava/dokuwiki-template-vector/issues/64

This snippet add the pagemenu-entries from plugins to list with links in the sidebar.

Furhermore, I made some changes to the last version of bookcreator, which support these links now as well.
