### ISSUE TITLE
Change maximum size of selctet pages

### ISSUE THREAD

**Issue by Zerremonde** [Klap-in/dokuwiki-plugin-bookcreator#29]
Hey mate, its me again.
my problem is, i wanted to create a pdf book with round about 180 pages but the selection stopped at 90 with kicking me out of the wiki and sending a cach failure, after clearing cach i could login again but the selection was gone.

Is there a possibility to change the size of selectet pages from 90 to 200?

regards 
Zerremonde

**Comment by rwoldu** [comment]
@Zerremonde : What do you do with links within the PDfs? I also have exported 3 PDFs and merged them afterwards, but then a link e.g. from PDF 1 to PDF 3 doesnt' work.
Have you maybe found a solution for that?
Thanks in advance!

**Comment by Klap-in** [comment]
Hmmm, That is updating of internal links in documents is a relatively new feature. It checks only for pages that are added to the generated PDF. 
The restricting on the number of pages per export is still there due to the use of cookies. 
A way that does not use cookies is by using exporting of a namespace (see wiki page for the url options). Of course that is only possible if you have ordered your pages per namespace.

**Comment by rwoldu** [comment]
Thank you very much for your message...I am not sure how to apply your suggestion, to be honest...and additionally, I think it maybe won't work as I have many namespaces that link to each other...
